name: CI/CD Pipeline for GCP VM

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GCP VM
        env:
          GCP_VM_IP: 34.58.167.132  # Replace with your actual VM IP
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        run: |
          echo "$GCP_SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$GCP_VM_IP << 'EOF'
            cd ~/test-node-app
            git pull origin main
            npm install
            pm2 restart all || pm2 start app.js --name "test-node-app"
            exit
          EOF
